// USER REDUCER TYPES
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

// UI REDUCER TYPES
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// DATA REDUCER TYPES
export const SET_MURMURS = "SET_MURMURS";
export const SET_MURMUR = "SET_MURMUR";
export const LOADING_DATA = "LOADING_DATA";
export const LIKE_MURMUR = "LIKE_MURMUR";
export const UNLIKE_MURMUR = "UNLIKE_MURMUR";
export const DELETE_MURMUR = "DELETE_MURMUR";